# Generated by Django 3.2.3 on 2021-05-24 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ('-id',)},
        ),
    ]
