# Generated by Django 3.2.3 on 2021-05-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data da Criação')),
                ('hora_criacao', models.TimeField(auto_now_add=True, verbose_name='Hora da Criação')),
                ('data_edicao', models.DateField(auto_now=True, verbose_name='Data da Edição')),
                ('hora_edicao', models.TimeField(auto_now=True, verbose_name='Hora da Edição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Preço')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('estoque', models.IntegerField(default=0, null=True, verbose_name='Estoque')),
                ('quantidade_vendida', models.PositiveIntegerField(default=0, null=True, verbose_name='Quantidade Vendida')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
