# Generated by Django 3.2.3 on 2021-05-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data da Criação')),
                ('hora_criacao', models.TimeField(auto_now_add=True, verbose_name='Hora da Criação')),
                ('data_edicao', models.DateField(auto_now=True, verbose_name='Data da Edição')),
                ('hora_edicao', models.TimeField(auto_now=True, verbose_name='Hora da Edição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descricao')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Produtos'},
        ),
    ]
